//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuiApp
{
    using System;
    using Mono.Terminal;
    using Terminal.Gui;
    
    
    public partial class Example1
    {
        
        private MenuItem closeMenutItem;
        
        private MenuBar mainMenuBar;
        
        private Window mainWindow;
        
        private Label ml;
        
        private Button cancelButton;
        
        partial void Button1_Clicked();
        
        partial void cancelButton_Clicked();
        
        partial void OnOpen();
        
        partial void OnClose();
        
        partial void OnExit();
        
        private void InitLayout()
        {
            MenuItem MenuItem1 = new MenuItem("Open", null, null);
            this.closeMenutItem = new MenuItem("Close", null, null);
            MenuItem MenuItem2 = new MenuItem("Exit", null, null);
            MenuBarItem MenuBarItem1 = new MenuBarItem("File", new MenuItem[] {
                        MenuItem1,
                        closeMenutItem,
                        MenuItem2});
            this.mainMenuBar = new MenuBar(new MenuBarItem[] {
                        MenuBarItem1});
            this.mainWindow = new Window("Hello");
            this.ml = new Label(new Rect(3,17, 47, 1), "Mouse: ");
            Label Label1 = new Label(new Rect(3,18, 47, 1), "Cursor: ");
            Label Label2 = new Label(new Rect(3,19, 47, 1), "Keyboard: ");
            Button Button1 = new Button(3, 19, "OK");
            this.cancelButton = new Button(3, 20, "Cancel");
            // mainWindow
            mainWindow.Add(ml);
            mainWindow.Add(Label1);
            mainWindow.Add(Label2);
            mainWindow.Add(Button1);
            mainWindow.Add(cancelButton);
            mainWindow.X = 0;
            mainWindow.Y = 1;
            mainWindow.Width = Dim.Fill();
            mainWindow.Height = Dim.Fill() - 1;
            // (Button1)
            Button1.Clicked = () => Button1_Clicked();
            // cancelButton
            cancelButton.Clicked = () => cancelButton_Clicked();
            // mainMenuBar
            MenuItem1.Action = () => OnOpen();
            closeMenutItem.Action = () => OnClose();
            MenuItem2.Action = () => OnExit();
        }
    }
}
